export const dealsData = [
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Hansaplast",
    agency: "Dharma Corner Stone",
    deliverables: "YT Integrated Video",
    link: "https://youtu.be/BTX3imkN6SM?si=Zbg0L5wq42XPzg0t",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Hansaplast",
    agency: "Dharma Corner Stone",
    deliverables: "YT Shorts",
    link: "Yet to share link",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 500000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Hansaplast",
    agency: "Dharma Corner Stone",
    deliverables: "Usage Rights 1 Mth",
    link: "NA",
    deliveryMonth: "Nov 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 400000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Tanvi",
    creatorName: "Farah Khan",
    campaign: "Cadbury Celebrations",
    agency: "White River Media",
    deliverables: "YT Integrated Video",
    link: "https://youtu.be/p8BPQTrRk40?si=2xKG0Ej85FyilLsi",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1300000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Tanvi",
    creatorName: "Archana Puran Singh",
    campaign: "Cadbury Celebrations",
    agency: "White River Media",
    deliverables: "YT Integrated Video",
    link: "https://www.youtube.com/watch?v=0ft_xhY9VAk",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 700000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti & Tanvi",
    creatorName: "Archana Puran Singh",
    campaign: "Plum Goodness",
    agency: "",
    deliverables: "YT Integrated Video",
    link: "https://www.youtube.com/watch?v=zr5LOmEhvMI",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 500000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "Usage Rights 1 Mth",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "Usage Rights 2 Mth",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "TOPS ketchep",
    agency: "Nibhaent",
    deliverables: "Usage Rights 3 Mth",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Google AI",
    agency: "Collective Artist",
    deliverables: "IG Reels",
    link: "https://www.instagram.com/reel/DPyk3_KkfNh/?igsh=MW95dGhreHFkd240MA==",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 2000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Google AI",
    agency: "Collective Artist",
    deliverables: "Usage Rights 1 Mth",
    link: "NA",
    deliveryMonth: "Nov 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 600000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Shreya Kalra",
    campaign: "Philips",
    agency: "Schbang",
    deliverables: "Non Collab reel",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 400000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Shreya Kalra",
    campaign: "Philips",
    agency: "Schbang",
    deliverables: "IG Video Story",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 75000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Shreya Kalra",
    campaign: "Bellavita",
    agency: "",
    deliverables: "IG Collab Reel",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 400000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Shreya Kalra",
    campaign: "Bellavita",
    agency: "",
    deliverables: "Usage Rights 1 Mth",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 75000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "FRIDO",
    agency: "Nibhaent",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "FRIDO",
    agency: "Nibhaent",
    deliverables: "Gifting Integration",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 300000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "FRIDO",
    agency: "Nibhaent",
    deliverables: "45 days usage",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 75000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "Flipkart Big bang Diwali",
    agency: "Kinnect Media",
    deliverables: "IG Collab Reel",
    link: "https://www.instagram.com/reel/DPoBW9xkipF/?igsh=MTJxeDg4NDc0ZXp0eQ==",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1500000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "Flipkart Big bang Diwali",
    agency: "Kinnect Media",
    deliverables: "IG Video Story",
    link: "Brand Deal Screenshots",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 400000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Farah Khan",
    campaign: "Flipkart Big bang Diwali",
    agency: "Kinnect Media",
    deliverables: "IG Video Story",
    link: "Brand Deal Screenshots",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 400000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Kurkure Jowar puff",
    agency: "Abridge",
    deliverables: "YT Dedicated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Kurkure Jowar puff",
    agency: "Abridge",
    deliverables: "Usage Rights 1 Mth",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 200000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Kurkure Jowar puff",
    agency: "Abridge",
    deliverables: "IG Video Story",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 600000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Mr.Faisu MG 3",
    campaign: "Dubai Tourism",
    agency: "Pulstry",
    deliverables: "IG Reels",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 200000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Mr.Faisu MG 3",
    campaign: "Dubai Tourism",
    agency: "Pulstry",
    deliverables: "IG Reels",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 200000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Mr.Faisu MG 3",
    campaign: "Dubai Tourism",
    agency: "Pulstry",
    deliverables: "IG Post",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Archana Puran Singh",
    campaign: "Rupay",
    agency: "ADCOUNTY MEDIA INDIA LIMITED",
    deliverables: "Tri Collab reel",
    link: "https://www.instagram.com/p/DP_cIa1jwMs/",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 770000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Aayushman Sethi",
    campaign: "Rupay",
    agency: "ADCOUNTY MEDIA INDIA LIMITED",
    deliverables: "Tri Collab reel",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 130000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Archana Puran Singh",
    campaign: "Ather",
    agency: "Oml Ent.",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 500000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Shreya/Rishabh",
    campaign: "Nivea",
    agency: "MSL",
    deliverables: "IG Collab Reel",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 560000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Shreya/Rishabh",
    campaign: "Nivea",
    agency: "MSL",
    deliverables: "Production Cost",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 10000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Farah Khan",
    campaign: "Sky Scanner",
    agency: "MSL",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Archana Puran Singh",
    campaign: "DishTv",
    agency: "Abridge",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 600000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Tanvi",
    creatorName: "Farah Khan",
    campaign: "Dot & Key",
    agency: "Dot & Key",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1200000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Shreya Kalra",
    campaign: "Song promotion - PAN india",
    agency: "Round clock",
    deliverables: "IG Reels",
    link: "https://www.instagram.com/reel/DQZdLjqDXdm/?igsh=MTg0NXBzN3Z4dDBzag==",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Mr.Faisu MG 3",
    campaign: "Song promotion",
    agency: "",
    deliverables: "IG Reels",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 275000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Kalp",
    creatorName: "Shreya Kalra",
    campaign: "Song promotion - Killa",
    agency: "Round clock",
    deliverables: "IG Reels",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 100000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Bhakti",
    creatorName: "Farah Khan",
    campaign: "Plum Goodness",
    agency: "",
    deliverables: "YT Integrated Video",
    link: "",
    deliveryMonth: "",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 1000000,
  },
  {
    dealMonth: "Oct 25",
    poc: "Sejal",
    creatorName: "Dr. Aman Khurana",
    campaign: "HK Vital",
    agency: "Marqueting Ventures",
    deliverables: "Usage Rights 1 Mth",
    link: "NA",
    deliveryMonth: "Oct 25",
    deliveryDate: "",
    paymentDue: "",
    remainingBusinessDays: "",
    paymentDate: "",
    dealSize: 15000,
  },
];

// Summary statistics
export const getSummaryStats = () => {
  const totalDealSize = dealsData.reduce((sum, deal) => sum + deal.dealSize, 0);
  const uniquePOCs = [...new Set(dealsData.map((deal) => deal.poc))];
  const uniqueCreators = [
    ...new Set(dealsData.map((deal) => deal.creatorName)),
  ];
  const uniqueCampaigns = [...new Set(dealsData.map((deal) => deal.campaign))];

  return {
    totalDealSize,
    totalDeals: dealsData.length,
    uniquePOCs: uniquePOCs.length,
    uniqueCreators: uniqueCreators.length,
    uniqueCampaigns: uniqueCampaigns.length,
    pocList: uniquePOCs,
    creatorList: uniqueCreators,
    campaignList: uniqueCampaigns,
  };
};
